export const continents = {
    AF: 'Africa',
    AS: 'Asia',
    EU: 'Europe',
    NA: 'North America',
    SA: 'South America',
    OC: 'Oceania',
  };
  
  export const countriesByContinent = {
    AF: [
      { code: 'ZA', name: 'South Africa' },
      { code: 'NG', name: 'Nigeria' },
      { code: 'EG', name: 'Egypt' },
      { code: 'KE', name: 'Kenya' },
      { code: 'GH', name: 'Ghana' },
      { code: 'DZ', name: 'Algeria' },
      { code: 'MA', name: 'Morocco' },
      { code: 'ET', name: 'Ethiopia' },
      { code: 'TN', name: 'Tunisia' },
      { code: 'UG', name: 'Uganda' },
      { code: 'SD', name: 'Sudan' },
      { code: 'CM', name: 'Cameroon' },
      { code: 'SN', name: 'Senegal' },
      { code: 'ZW', name: 'Zimbabwe' },
      { code: 'ZM', name: 'Zambia' },
    ],
    AS: [
      { code: 'IN', name: 'India' },
      { code: 'JP', name: 'Japan' },
      { code: 'CN', name: 'China' },
      { code: 'KR', name: 'South Korea' },
      { code: 'ID', name: 'Indonesia' },
      { code: 'TH', name: 'Thailand' },
      { code: 'PK', name: 'Pakistan' },
      { code: 'VN', name: 'Vietnam' },
      { code: 'BD', name: 'Bangladesh' },
      { code: 'PH', name: 'Philippines' },
      { code: 'MY', name: 'Malaysia' },
      { code: 'SG', name: 'Singapore' },
      { code: 'SA', name: 'Saudi Arabia' },
      { code: 'AE', name: 'United Arab Emirates' },
      { code: 'IQ', name: 'Iraq' },
    ],
    EU: [
      { code: 'GB', name: 'United Kingdom' },
      { code: 'DE', name: 'Germany' },
      { code: 'FR', name: 'France' },
      { code: 'IT', name: 'Italy' },
      { code: 'ES', name: 'Spain' },
      { code: 'NL', name: 'Netherlands' },
      { code: 'SE', name: 'Sweden' },
      { code: 'PL', name: 'Poland' },
      { code: 'BE', name: 'Belgium' },
      { code: 'AT', name: 'Austria' },
      { code: 'CH', name: 'Switzerland' },
      { code: 'NO', name: 'Norway' },
      { code: 'DK', name: 'Denmark' },
      { code: 'PT', name: 'Portugal' },
      { code: 'FI', name: 'Finland' },
    ],
    NA: [
      { code: 'US', name: 'United States' },
      { code: 'CA', name: 'Canada' },
      { code: 'MX', name: 'Mexico' },
      { code: 'CU', name: 'Cuba' },
      { code: 'GT', name: 'Guatemala' },
      { code: 'DO', name: 'Dominican Republic' },
      { code: 'HN', name: 'Honduras' },
      { code: 'JM', name: 'Jamaica' },
      { code: 'CR', name: 'Costa Rica' },
      { code: 'PA', name: 'Panama' },
      { code: 'NI', name: 'Nicaragua' },
      { code: 'SV', name: 'El Salvador' },
      { code: 'HT', name: 'Haiti' },
      { code: 'BZ', name: 'Belize' },
      { code: 'BB', name: 'Barbados' },
    ],
    SA: [
      { code: 'BR', name: 'Brazil' },
      { code: 'AR', name: 'Argentina' },
      { code: 'CO', name: 'Colombia' },
      { code: 'PE', name: 'Peru' },
      { code: 'VE', name: 'Venezuela' },
      { code: 'CL', name: 'Chile' },
      { code: 'EC', name: 'Ecuador' },
      { code: 'BO', name: 'Bolivia' },
      { code: 'PY', name: 'Paraguay' },
      { code: 'UY', name: 'Uruguay' },
      { code: 'GY', name: 'Guyana' },
      { code: 'SR', name: 'Suriname' },
      { code: 'GF', name: 'French Guiana' },
      { code: 'FK', name: 'Falkland Islands' },
      { code: 'BZ', name: 'Belize' },
    ],
    OC: [
      { code: 'AU', name: 'Australia' },
      { code: 'NZ', name: 'New Zealand' },
      { code: 'FJ', name: 'Fiji' },
      { code: 'PG', name: 'Papua New Guinea' },
      { code: 'SB', name: 'Solomon Islands' },
      { code: 'VU', name: 'Vanuatu' },
      { code: 'WS', name: 'Samoa' },
      { code: 'TO', name: 'Tonga' },
      { code: 'KI', name: 'Kiribati' },
      { code: 'TV', name: 'Tuvalu' },
      { code: 'NR', name: 'Nauru' },
      { code: 'MH', name: 'Marshall Islands' },
      { code: 'FM', name: 'Micronesia' },
      { code: 'PW', name: 'Palau' },
      { code: 'NC', name: 'New Caledonia' },
    ],
};
